interface Window {
    ActionView: import("../public/views/control/action")
    ActionsView: import("../public/views/control/actions")
    ControlView: import("../public/views/control")
    DiscordChannelView: import("../public/views/control/discord-channel")
    DiscordChannelsView: import("../public/views/control/discord-channels")
    GameView: import("../public/views/home/game")
    GameInfoView: import("../public/views/home/game/info")
    GameNotificationView: import("../public/views/home/game/notification")
    GameRecentView: import("../public/views/home/game/recent")
    GameSpotifyView: import("../public/views/home/game/spotify")
    GameSupportView: import("../public/views/home/game/support")
    GameTitleView: import("../public/views/home/game/title")
    HomeView: import("../public/views/home")
    IndexView: import("../public/views/index")
    IntroView: import("../public/views/home/intro")
    MethodNotAllowedView: import("../public/views/405")
    NotFoundView: import("../public/views/404")
    OverlayView: import("../public/views/overlay")
    RoncliGamingView: import("../public/views/control/roncli-gaming")
    ServerErrorView: import("../public/views/500")
    SpotifyPlaylistView: import("../public/views/control/spotify-playlist")
    SpotifyPlaylistsView: import("../public/views/control/spotify-playlists")
}
